import Header from '@/components/Header'
import './globals.css'

import { Inter } from 'next/font/google'
import { OneSignalContextProvider } from '@/lib/Context/oneSignal'


// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const dynamic = 'force-dynamic'

export default function RootLayout({ children }: { children: React.ReactNode }) {



  return (
    <html lang="se">
      <body className={inter.className}>
        <Header />
        <main>
          <OneSignalContextProvider>
            {children}
          </OneSignalContextProvider>
        </main>
      </body>
    </html>
  )
}