import Header from '@/components/Header'
import './globals.css'
import { User, createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  const supabase = createServerComponentClient({ cookies })

  const {
      data: { user },
  } = await supabase.auth.getUser()

  return (
    <html lang="en">
      <body>
        <Header user={user} />
        <main className="min-h-screen bg-background flex flex-col items-center">
          {children}
        </main>
      </body>
    </html>
  )
}
